package christmas.domain.constants.event;

public enum EventConstants {
    DECEMBER(12),
    DECEMBER_FIRST_DAY(1),
    DECEMBER_LAST_DAY(31),
    DECEMBER_FIRST_DAY_OF_WEEK_INDEX(5),

    GENERAL_EVENT_START_DAY(1),
    GENERAL_EVENT_END_DAY(31),
    CHRISTMAS_EVENT_START_DAY(1),
    CHRISTMAS_EVENT_END_DAY(25),

    CHRISTMAS_DISCOUNT_START_AMOUNT(1_000),
    CHRISTMAS_DISCOUNT_INCREMENT(100),

    WEEKDAY_DISCOUNT_AMOUNT(2_023),
    WEEKEND_DISCOUNT_AMOUNT(2_023),
    SUNDAY_INDEX(0),
    MONDAY_INDEX(1),
    TUESDAY_INDEX(2),
    WEDNESDAY_INDEX(3),
    THURSDAY_INDEX(4),
    FRIDAY_INDEX(5),
    SATURDAY_INDEX(6),

    SPECIAL_DISCOUNT_AMOUNT(1_000),
    SPECIAL_DATE_ONE(3),
    SPECIAL_DATE_TWO(10),
    SPECIAL_DATE_THREE(17),
    SPECIAL_DATE_FOUR(24),
    SPECIAL_DATE_FIVE(25),
    SPECIAL_DATE_SIX(31),

    GIFT_REWARD_CHAMPAGNE_THRESHOLD(120_000),

    BADGE_REWARD_STAR_THRESHOLD(5_000),
    BADGE_REWARD_TREE_THRESHOLD(10_000),
    BADGE_REWARD_SANTA_THRESHOLD(20_000);

    private final int value;

    EventConstants(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
